[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
semantic_analysis = { path = "../semantic_analysis" }
errors = { path = "../errors" }
