[workspace]
resolver = "1"
members = [
  "butter", # The engine

  "margarine", # The Language
  "margarine/common",
  "margarine/lexer",
  "margarine/parser",
  "margarine/semantic_analysis",
  # "margarine/ir",
  # "margarine/codegen",
  "margarine/errors",
  "margarine/runtime",
]