[workspace]
resolver = "1"
default-members = [
    "margarine",
]

members = [
    "margarine",
    "margarine/common",
    "margarine/common/derive",
    "margarine/lexer",
    "margarine/parser",
    "margarine/semantic_analysis",
    "margarine/errors",
    "margarine/runtime",
    "fuzz",
]


