[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[features]
stack_arena_tracking = []

[dependencies]
bytemuck = "*"
common = { path = "../common" }
sti = { git = "https://github.com/leddoo/sti" }
