[package]
name = "semantic_analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
errors = { path = "../errors" }
parser = { path = "../parser" }
lexer  = { path = "../lexer" }
sti = { git = "https://github.com/leddoo/sti" }
llvm-api = { path = "../llvm-api" }
